### ISSUE TITLE
Is it possible to choose a specific audio from a multi audio vid?

### ISSUE THREAD

**Issue by Nenokkadine** [tks18/gindex-v4#102]

**Comment by tks18** [comment]
Nope not possible

**Comment by Nenokkadine** [comment]
Bro Video Quality Switching really works or Its a Dummy One 🤔

**Comment by tks18** [comment]
That depends on the format of video bro.
Mkv formats are not capable. 
I think mpeg will do but there will be no major reduction in quality and bandwidth

**Comment by Nenokkadine** [comment]
![G-Index and 4 more pages - mails - Microsoft​ Edge 2020-07-09 22-20-07](https://user-images.githubusercontent.com/65813999/87068740-a7a5c100-c233-11ea-93aa-a9c3cb0e5e65.gif)
Bro Some MKV Files are Playing but some are not playing Here is an Example above

**Comment by tks18** [comment]
That depends on how the video is encoded. If the browser supports then it will play otherwise it cannot.
Afterall its a web player. So it depends on the browser
