### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by DaleHenry** [tks18/gindex-v4#105]
![Annotation 2020-07-12 183105](https://user-images.githubusercontent.com/59341073/87247043-ea071200-c46e-11ea-9f7e-a330bfd161e4.jpg)

I followed all the steps in the wiki and when I try to login using my admin email, I get this error.
What have I done wrong.

**Comment by theRay1s** [comment]
Remove / from end of all links in vars

**Comment by adisubagja** [comment]
> Remove / from end of all links in vars

Var frontend index.js or backend heroku?

**Comment by tks18** [comment]
Both,
In worker file check for backendsite,
In heroku check frontendurl variable

**Comment by adisubagja** [comment]
Can show example sir im trying this same a problem

**Comment by DaleHenry** [comment]
I changed vars in heroku, still same error. Do I need to do anything than save changes for it to come in effect? Worker file is okay.

**Comment by theRay1s** [comment]
@DaleHenry change from index.js too from frontend 

Remove / from backend site url

**Comment by DaleHenry** [comment]
Yeah I am sorry but the error is fixed, I used the wrong frontend URL( had another one).
Again extremely sorry.

Closing the issue now.
