### ISSUE TITLE
Options to select different categories for different roots

### ISSUE THREAD

**Issue by em108** [tks18/gindex-v4#109]
**Is your feature request related to a problem? Please describe.**
Currently if you select a different root folder, the options on the home page you had earlier hard linked in the categories remain the same thereby being rendered useless if you navigate to another root folder / Team Drive of your choice.

**Describe the solution you'd like**
I think an option to select different categories for different root folders would be a nice addition. Say you navigate to a different root folder / team drive, the home page switches with the different categories you had hard linked for that specific root folder. 

*For example:*
 Say another root folder for Courses, the home page switches with your newly selected options and subcategories.

**Describe alternatives you've considered**
None at the moment

**Additional context**
None at the moment

_Thanks for the development. It's really a handy and fast responsive index :)_

**Comment by tks18** [comment]
Currently working on !! 
Please Wait till i give support for multiple drives

**Comment by em108** [comment]
Ooo, thanks for the response. Thanks once again 😬
