### ISSUE TITLE
Site without the Backend server

### ISSUE THREAD

**Issue by S4MUR411** [tks18/gindex-v4#110]
First let me start with how beautiful your project is, this is the best google drive index i have seen so far in term of look and functionality.

It would be better for some people if there was no need for the registration (the Backend server), don't get me wrong its a great feature but setting up for some people gets real complicated. (me)

it would be much easier to setup and browse the site without the backend system(no need or registration and account). simply just visit the site and stream or download the files. (if someone wants to use it just as a personal site and stream or download his/her file)

it would be great if you could make another brunch of the project and modify it to make it usable it without the backend server 
( i have no knowledge of coding so i don't know how hard it is to modify it so forgive my ignorance)

**Comment by tks18** [comment]
Ok will try that 🤟🤟

**Comment by S4MUR411** [comment]
wow, thank you, you are on fire.

**Comment by tks18** [comment]
> wow, thank you, you are on fire.

Here You Go.
https://github.com/tks18/gindex-v4-no-backend.
