### ISSUE TITLE
Page Not Loading 

### ISSUE THREAD

**Issue by Nenokkadine** [tks18/gindex-v4#113]
![image](https://user-images.githubusercontent.com/65813999/87642342-0359d800-c767-11ea-9cb3-50427dbe5b7c.png)
I am Using the Latest 7.7.4 Worker File

**Comment by tks18** [comment]
You have given any of these : 
‘ “ : 
Do not use these in any of the variables

**Comment by DaleHenry** [comment]
How long will the changes that I made in the page take to load in the index. I changed the all the trending and main hero posters and content and all I get is an empty page.

Also a noob doubt, should the version in worker file be 7.7.2 or 7.7.4

**Comment by Nenokkadine** [comment]
> You would have given any of these :
> ‘ “ :
> Do not use these in any of the variables
> Also there are so many changes in worker file you have to copy my worker file newly

I Changed all the Worker and Replaced and Replaced AuthConfig in that with the old one

**Comment by tks18** [comment]
Ok i will check

**Comment by tks18** [comment]
> How long will the changes that I made in the page take to load in the index. I changed the all the trending and main hero posters and content and all I get is an empty page.
> 
> Also a noob doubt, should the version in worker file be 7.7.2 or 7.7.4



> > You would have given any of these :
> > ‘ “ :
> > Do not use these in any of the variables
> > Also there are so many changes in worker file you have to copy my worker file newly
> 
> I Changed all the Worker and Replaced AuthConfig in that with the old one

Ok that's a spelling mistake 
I have fixed that now it will work

**Comment by Nenokkadine** [comment]
![image](https://user-images.githubusercontent.com/65813999/87655683-2fc92080-c776-11ea-898c-1c600b002750.png)
this is the Process for adding Links from Multiple Drives right?

**Comment by tks18** [comment]
> ![image](https://user-images.githubusercontent.com/65813999/87655683-2fc92080-c776-11ea-898c-1c600b002750.png)
> this is the Process for adding Links from Multiple Drives right?

Yess

**Comment by Nenokkadine** [comment]
I Found out Some issues in the admin panel.
1)Manage Existing User Panel misalignment 
![image](https://user-images.githubusercontent.com/65813999/87664413-d4e9f600-c782-11ea-8ba1-6b2f456b9179.png)
When I set Page zoom to 110% its Good. But Less than 110 causing this issue.

2)Inviting Users
This is a doubt causing the issue
When inviting a Admin or super admin It is showing that "No user found". When i use the same mail and Invited as User the mail is being Sent
Inviting as a User
![image](https://user-images.githubusercontent.com/65813999/87664982-ca7c2c00-c783-11ea-91bf-3d50cafd93f3.png)
Inviting as an Super Admin
![image](https://user-images.githubusercontent.com/65813999/87665063-ec75ae80-c783-11ea-9ef1-7dce1d8f7545.png)

Is this mean that while inviting a admin or super admin. he has to be a User first?

**Comment by tks18** [comment]
It because of heirarchy in roles 
Only user can be invited as admin and only admins can be invited as superadmin

**Comment by Nenokkadine** [comment]
> It because of heirarchy in roles
> Only user can be invited as admin and only admins can be invited as superadmin

What About the first one🤔

**Comment by tks18** [comment]
> > It because of heirarchy in roles
> > Only user can be invited as admin and only admins can be invited as superadmin
> 
> What About the first one

I didn't get that issue 
I keep at 100% only

**Comment by Nenokkadine** [comment]
> > > It because of heirarchy in roles
> > > Only user can be invited as admin and only admins can be invited as superadmin
> > 
> > 
> > What About the first one
> 
> I didn't get that issue
> I keep at 100% only

I Tried Checking it with Both Edge Chromium and Chrome Both are Showing the same :(
When i Tried with old Edge its not even rendering  the site 😂.

**Comment by DaleHenry** [comment]
> > > It because of heirarchy in roles
> > > Only user can be invited as admin and only admins can be invited as superadmin
> > 
> > 
> > What About the first one
> 
> I didn't get that issue
> I keep at 100% only

I can also report the same issue in opera 
![Annotation 2020-07-17 172819](https://user-images.githubusercontent.com/59341073/87784197-76d91380-c853-11ea-9d50-991a6ed6782b.jpg)
![InkedAnnotation 2020-07-17 1728129_LI](https://user-images.githubusercontent.com/59341073/87784199-78a2d700-c853-11ea-9a1d-9c45a4f58225.jpg)

I know its defenitely not a big issue, but just wanted to spot this out.

Amazing last updates. Great work.

**Comment by tks18** [comment]
> > > > It because of heirarchy in roles
> > > > Only user can be invited as admin and only admins can be invited as superadmin
> > > 
> > > 
> > > What About the first one
> > 
> > 
> > I didn't get that issue
> > I keep at 100% only
> 
> I can also report the same issue in opera
> ![Annotation 2020-07-17 172819](https://user-images.githubusercontent.com/59341073/87784197-76d91380-c853-11ea-9d50-991a6ed6782b.jpg)
> ![InkedAnnotation 2020-07-17 1728129_LI](https://user-images.githubusercontent.com/59341073/87784199-78a2d700-c853-11ea-9a1d-9c45a4f58225.jpg)
> 
> I know its defenitely not a big issue, but just wanted to spot this out.
> 
> Amazing last updates. Great work.

I fixed that in latest update
