### ISSUE TITLE
Advertisement banners or code? No Search Option?

### ISSUE THREAD

**Issue by askfriends** [tks18/gindex-v4#118]
I have just finsihed setting this up while reading your guide. If possible please add link to this guide in ReadMe.

Now coming back to question, 

1.can we add advertisement banners or code at main positions like in header, below video player, left/right and footer etc?

2. Also i couldn't see Search option, have you not yet implemented it or i just missed it?

3. Can we change Loading gif?

4. what is hybridpass field in the main script?

**Comment by tks18** [comment]
1. Why you need to display advertisement is this index ?
2. Search is only available for Root and not a Folder.
3. Yes you can change in the worker file.
4. That is just for anonymous login.

**Comment by askfriends** [comment]
> 1. Why you need to display advertisement is this index ?
> 2. Search is only available for Root and not a Folder.
> 3. Yes you can change in the worker file.
> 4. That is just for anonymous login.

Thanks for the reply.
1. You mean we cant make index site public? if we can make it public than its nice idea to implement advertisement system, and also it would be great if you could add link advertisement support, if user click on any movie to watch, it will go through advertisement page and then visit actual movie page. for example adf.ly linkvertise and many others.
2. It would be nice to have Search function on every page, it helps to find content easily.
3. yes i found the code and changed it. Thanks
4. Got it..

**Comment by tks18** [comment]
Search function only works on root thats the limitation of Drive api 
We can't do anything for that

**Comment by PrathamH** [comment]
> > 1. Why you need to display advertisement is this index ?
> > 2. Search is only available for Root and not a Folder.
> > 3. Yes you can change in the worker file.
> > 4. That is just for anonymous login.
> 
> Thanks for the reply.
> 
> 1. You mean we cant make index site public? if we can make it public than its nice idea to implement advertisement system, and also it would be great if you could add link advertisement support, if user click on any movie to watch, it will go through advertisement page and then visit actual movie page. for example adf.ly linkvertise and many others.
> 2. It would be nice to have Search function on every page, it helps to find content easily.
> 3. yes i found the code and changed it. Thanks
> 4. Got it..

To make index site public you should use no-backend version

**Comment by askfriends** [comment]
> > > 1. Why you need to display advertisement is this index ?
> > > 2. Search is only available for Root and not a Folder.
> > > 3. Yes you can change in the worker file.
> > > 4. That is just for anonymous login.
> > 
> > 
> > Thanks for the reply.
> > 
> > 1. You mean we cant make index site public? if we can make it public than its nice idea to implement advertisement system, and also it would be great if you could add link advertisement support, if user click on any movie to watch, it will go through advertisement page and then visit actual movie page. for example adf.ly linkvertise and many others.
> > 2. It would be nice to have Search function on every page, it helps to find content easily.
> > 3. yes i found the code and changed it. Thanks
> > 4. Got it..
> 
> To make index site public you should use no-backend version

Yeah thanks for the suggestion and you are right.
but i wanna know is there any way to edit and use some code to show some banners in top, left, right and bottom side of every page?
