### ISSUE TITLE
Feature requests and ideas

### ISSUE THREAD

**Issue by archie9211** [tks18/gindex-v4#121]
When we are watching an episode from a folder. the listing of next items on left panel "Continue you binge" are randomly shuffled. 
Can it be shown in sorted manner as we see the files in folder. 

Thanks.

**Comment by tks18** [comment]
Yaa Can Be Done !

**Comment by archie9211** [comment]
very well. Hope to see this implemented soon.

**Comment by tks18** [comment]
I thought shuffling that will give a youtube like feel.

**Comment by archie9211** [comment]
Yes, But when watching some series, it will be better if next episode is next to it..

**Comment by tks18** [comment]
Ya i understand

**Comment by archie9211** [comment]
I know it so much to ask but this feature will be really handy.

Google drive api provide read/write access. 

1. Ability of admins/superadmins to modify the content from website. (rearranging the folders and files)


I will be adding more here. Not all of them will be feasible. But still.

Also websites quick links, admin panel and categories buttons are not responsive enough. when we click, it seems like nothing is going on and then suddenly new page comes. (may be some loading bar or somthing will be great)

**Comment by tks18** [comment]
Okay, 
Will Provide a Loading Animation for that.

**Comment by archie9211** [comment]
> Also websites quick links, admin panel and categories buttons are not responsive enough. when we click, it seems like nothing is going on and then suddenly new page comes. (may be some loading bar or somthing will be great)

Same happens when browsing folders.

**Comment by tks18** [comment]
> > Also websites quick links, admin panel and categories buttons are not responsive enough. when we click, it seems like nothing is going on and then suddenly new page comes. (may be some loading bar or somthing will be great)
> 
> Same happens when browsing folders.

Will make the website faster in the coming updates
