### ISSUE TITLE
DTS Audio Codex Not Supported ? 

### ISSUE THREAD

**Issue by noobvishal** [tks18/gindex-v4#132]
**DTS Audio Not Playing**
Video Files With DTS Audio Codex Do Not Play Any Sound.

**Example Filename**
Guardians.Of.The.Galaxy.2014.1080p.BRRip.x264.DTS-JYK.mkv

**P.S:** _I Am Not Sure If This Is The Limitation Of The Browser Or It Can Be Fixed._

**Comment by tks18** [comment]
Bro ofcourse that is the limitation of the browser

**Comment by noobvishal** [comment]
Okay, Thanks For The Reply 👍
