### ISSUE TITLE
Can we add monthly based subscription option for all registered users?

### ISSUE THREAD

**Issue by askfriends** [tks18/gindex-v4#140]
It would be nice if we could add montly/weekly based subscription option for all registered users, like when user registers an acoount, ADMIN HAVE OPTION TO ALLOT WEEKLY/MONTHLY subscription. There must also be an option to renew existing account.
And after the period is over their account must be disabled.

**Comment by tks18** [comment]
Everything is possible.
But why you need that much controllability over users

**Comment by askfriends** [comment]
> Everything is possible.
> But why you need that much controllability over users

we can give access to users based on the time period, it will definitely make this project on next level.
