### ISSUE TITLE
Page Source reveals important info which must be encrypted

### ISSUE THREAD

**Issue by askfriends** [tks18/gindex-v4#141]
If you go to page source, it reveals heroku app information and other important information about backened services, so is it not possible to encrypt that data with base64 or any other method?

**Comment by tks18** [comment]
What it reveals 😳

**Comment by askfriends** [comment]
> What it reveals 😳
> They can't access without authorisation. Then why
> Also what is there important

I know its not that serious but i dont want visitors may know what service and backened im using.
If its possible than why not encrypt that to avoid any possible info leak.
