### ISSUE TITLE
Add a SORT feature to the folders

### ISSUE THREAD

**Issue by sneakyGrit** [tks18/gindex-v4#166]
Folders have a Sort icon but I guess it is not implemented yet. Please implement this- it will take hardly 5min of your time but will save a lot of time for the users, like I am watching lectures on the site and because of lack of sorting I have go back and check what should I watch next. This decreases User experience.

**Comment by askfriends** [comment]
+1

**Comment by tks18** [comment]
@askfriends @sneakyGrit 

Look out the latest pre-release

**Comment by sneakyGrit** [comment]
> @askfriends @sneakyGrit
> 
> Look out the latest pre-release

Thanks man! Btw, when is the release expected?

**Comment by askfriends** [comment]
> @askfriends @sneakyGrit
> 
> Look out the latest pre-release

Thanks..hope to see next stable release soon.
Thanks a ton for your hard work
