### ISSUE TITLE
Backend Not Found

### ISSUE THREAD

**Issue by sourav1337** [tks18/gindex-v4#183]
Why I see 404 Not Found on your backend repo https://github.com/tks18/gindex-backend ?

**Comment by tks18** [comment]
I have made that private
I started this project expecting people will use it for educational or personal purposes only

But it has gone too much that so many have started using this project for making money commercializing it.

Its my hardwork creating this whole project. I spent literally for 3 months for this whole project and i don't want my project to be misused. 

Thats all

**Comment by sourav1337** [comment]
I use it for my personal usage only? Can I get access please?

**Comment by tks18** [comment]
Absolutely you can use it for personal purposes. 

Email me.

**Comment by missemily2022** [comment]
@tks18 I want the Backend Project for Personal Use Can I please get  it?

**Comment by tks18** [comment]
Ofcourse you can just clone the backend branch of gindex-v4

https://github.com/tks18/gindex-v4/tree/backend
