### ISSUE TITLE
Frontend(worker) auto updater

### ISSUE THREAD

**Issue by ahnaf0014** [tks18/gindex-v4#208]
It will be great if there is a tool for auto updating frontend like cli tool for backend.
Don't want to change user credentials and images link that I manually provided.I just want it to upgrade with the newest frontend release.

**Comment by tks18** [comment]
You Don't need to Change Everything in Frontend for Every Update. You Just Need to Update the Version in that to Latest. For that a tool will be Too Much

**Comment by ahnaf0014** [comment]
> You Don't need to Change Everything in Frontend for Every Update. You Just Need to Update the Version in that to Latest. For that a tool will be Too Much

Ohh didn't know about that,,tnx for informing

**Comment by tks18** [comment]
👍👍
