### ISSUE TITLE
It says "it looks like the recipient mail is spam"

### ISSUE THREAD

**Issue by Rpingat** [tks18/gindex-v4#215]
I don't know why I'm facing this while adding a new user help appreciated

**Comment by tks18** [comment]
Either your mail provider is not allowing to send the mail to that recipient or your are not authenticated to send that mail 

Check mail credentials

**Comment by Rpingat** [comment]
I used yandex but wasn't working and now shifted to Yahoo it's working flawlessly

**Comment by tks18** [comment]
Yup it's the problem

**Comment by shyam2511** [comment]
> I used yandex but wasn't working and now shifted to Yahoo it's working flawlessly

@Rpingat Can you guide me as to what exactly you used as yahoo smtp settings; as I am getting the same problem.
TIA!

**Comment by tks18** [comment]
Incase of Yahoo, You need to Generate App Password in your Yahoo Account and Put that password in backend vars, Then you will be able

**Comment by ronin08** [comment]
even that doesn't work , same "receipent email is spam" message appears !

**Comment by ronin08** [comment]
> I used yandex but wasn't working and now shifted to Yahoo it's working flawlessly

can you please tell your smtp configs ....  I am also using Yahoo ,still facing problem
