### ISSUE TITLE
Unable to connect to tks18/gindex-backend 

### ISSUE THREAD

**Issue by atmos-o** [tks18/gindex-v4#233]
Following the guide: https://telegra.ph/Google-Drive-Ultimate-Index-07-04
No links work to deploy the backend.

![image](https://user-images.githubusercontent.com/44858581/113520603-1b3ee980-958c-11eb-847b-1c30870fed87.png)

**Comment by tks18** [comment]
Go to Releases in this Repo.
You will find the Backend Release, Download and deploy to heroku
