### ISSUE TITLE
Email detected as spam

### ISSUE THREAD

**Issue by shyam2511** [tks18/gindex-v4#240]
When accepting user into frontend the user email is incorrectly labelled as spam. 
(Screenshot Attached)
![Screenshot 2021-04-14 230209](https://user-images.githubusercontent.com/67902666/114754902-b39c5180-9d76-11eb-9c11-ac205d06fad0.png)

**Comment by shyam2511** [comment]
Tried using yahoo as well as aol as network providers, still no difference observed.

**Comment by tks18** [comment]
See #215
