### ISSUE TITLE
TMDB Posters Not Visible

### ISSUE THREAD

**Issue by blinditachi** [tks18/gindex-v4#244]
everything works fine except when I CLICK "Go To Drive" it keeps reloading the page. Is there any fix?

**Comment by tks18** [comment]
Then something is wrong with drive api credentials

**Comment by Technopope** [comment]
Can confirm a similar issue, I've tried to replace Oauth credentials atleast thrice and have used rclone before, but the Drive page keeps refreshing, with a 500 to the `0:/` URL and with the error, The browser console shows the filed request's payload as this - http://prntscr.com/14cu2fz

**Comment by ronin08** [comment]
@tks18 same issue , when I click 'go to drive' it keeps getting reloading and refreshing ... 

what can be wrong with the api credentials , I have cross-checked it ... 
any idea ... please help

**Comment by tks18** [comment]
First of all in the refresh token field check whether you are giving the refresh token and not the Authorization code

FYI 
Auth code will be shorter, Refresh token will be longer

Also check whether you are using the same creds anywhere else then try generating a new oauth client id and generate a refresh token for that.

Try this and tell

**Comment by ronin08** [comment]
thanks man for the quick reply ... actually I was putting up the whole token given by the rclone config instead of "refresh_token" :) , Now it's all fine .

Everything is intact at its place , movie details , trailers but I can't see movie posters , actors-crew photos  .
Only production companies logo is visible .

**Comment by tks18** [comment]
I will check this 

> thanks man for the quick reply ... actually I was putting up the whole token given by the rclone config instead of "refresh_token" :) , Now it's all fine .
> 
> Everything is intact at its place , movie details , trailers but I can't see movie posters , actors-crew photos .
> Only production companies logo is visible .

**Comment by ronin08** [comment]
Why I am not seeing 'pending users' tab . I have requested access from a account , but neither received the email nor I can find the request in the admin tab . how to approve the  request .

https://telegra.ph/file/25a9008ee65a5c8d4d5f8.jpg

**Comment by tks18** [comment]
Go to add users
In that left side you will pending users list button in that you can take actions regarding accepting or denying access

**Comment by ronin08** [comment]
ohk .. got it .. but why don't I received the request mail ?

**Comment by tks18** [comment]
Check your spam

**Comment by ronin08** [comment]
not there too ... 
the mail should come to the 'ADMINEMAIL' na ?

**Comment by tks18** [comment]
Yup it should

(Sent from Mobile)

**Comment by ronin08** [comment]
another issue/bug , it doesn't play songs in queue/playlists .. just shows a error , skips every song and finally replays the original selected song .

https://telegra.ph/file/d576d7d0e2dc3e997778b.jpg
