### ISSUE TITLE
Stuck after login

### ISSUE THREAD

**Issue by stickyfin** [tks18/gindex-v4#245]
![image](https://user-images.githubusercontent.com/38528050/117064405-bf1ce000-ad58-11eb-93d8-759767a256bd.png)

I got stuck after logging in. The FRONTENDURL has been configured as stated in the wiki without / at the back.

**Comment by tks18** [comment]
Also Check You have Properly Added Frontendurl in Backend  Variables

**Comment by stickyfin** [comment]
Frontendurl variable in Backend variables also has been configured as per in instructions.

**Comment by stickyfin** [comment]
Issue solved by updating the mongodb url. But now stuck with Hybrid Password Is Wrong error message.
![image](https://user-images.githubusercontent.com/38528050/117105067-dcc96400-adaf-11eb-848f-89bd85022633.png)

**Comment by stickyfin** [comment]
Issue solved!

**Comment by TargetX25** [comment]
> Issue solved!
Is your otp is coming?
