### ISSUE TITLE
Email is not getting sento to admins to register a user

### ISSUE THREAD

**Issue by TargetX25** [tks18/gindex-v4#258]
Even though my backend server is working complete and my eamil Credentials are also correct i checked them many times but whenever a user request access to my index , verification email doesn't to go to admin mail to register the user i tried different mails providers too but same result ,i also used app password but still it didn't work . Please suggest me a soln....

**Comment by tks18** [comment]
You can connect any email with a smtp api provider like sendgrid

With that you can send emails from our app

**Comment by TargetX25** [comment]
> You can connect any email with a smtp api provider like sendgrid
> 
> With that you can send emails from our app

I tried already sir ,its not working

**Comment by tks18** [comment]
I have been using that for more than a year

**Comment by TargetX25** [comment]
> I have been using that for more than a year

I have been using yandex ,its not working..Can you tell me sir which mail provider are you using , i can try with that?

**Comment by tks18** [comment]
Yandex by itself won't allow sending automated emails .
I am using yandex with sendinblue smtp api. With that i was able to
