### ISSUE TITLE
Try to Provide a option to customize to Accent Color

### ISSUE THREAD

**Issue by Nenokkadine** [tks18/gindex-v4#74]

**Comment by tks18** [comment]
Bro,
Currently I am Working on Some other Features.
I will definitely provide that feature
Btw accent color can be easily changed in Index.sass file.
In that case u need to build the assets everytime you release

**Comment by Nenokkadine** [comment]
![image](https://user-images.githubusercontent.com/65813999/86568974-58d5fe00-bf8b-11ea-831c-deef11c516a0.png)
Invite Users is Still in Development ? or I am Not Getting it?

**Comment by tks18** [comment]
I think its a typo error from my side, will solve that. 
Will fix that today !.

**Comment by Nenokkadine** [comment]
and One Thing regarding  QuickLinks 
"{
        displayname: "Anime", // Name to Display
        link: "Anime", // Note: This is Case Sensitive .Give Drive Folder Name Here from Default Drive.
        faIcon: "fas fa-heart", // Font Awesome Icon Class
      },"
I Have movie folder in my team drive and its Not Redirecting to Movie folder and it is coming back to home

Movie is a Sub folder of a main folder is this causing the error

**Comment by tks18** [comment]
> and One Thing regarding QuickLinks
> "{
> displayname: "Anime", // Name to Display
> link: "Anime", // Note: This is Case Sensitive .Give Drive Folder Name Here from Default Drive.
> faIcon: "fas fa-heart", // Font Awesome Icon Class
> },"
> I Have set the "link" to Movie
> I Have movie folder in my team drive and its Not Redirecting to Movie folder and it is coming back to home
> 
> Movie is a Sub folder of a main folder is this causing the error

Yes that's the issue

**Comment by Nenokkadine** [comment]
Haa Thanks
