### ISSUE TITLE
h.265 video support

### ISSUE THREAD

**Issue by mlwbd** [tks18/gindex-v4#83]
Hey, can we see h.265 encoded video support on this index.
Sadly all index code out there are failed to support h.265 videos.

**Comment by tks18** [comment]
No, no browser supports H.265. And wide support is not likely to be added in the near future.

**Comment by mlwbd** [comment]
Hey, there should be support for copying link of folder, if in case we want to go fo specific location or share with other user,....like other index sites

**Comment by tks18** [comment]
Ya its there

**Comment by tks18** [comment]
See there's a button for share link
![Screenshot_20200703-000228](https://user-images.githubusercontent.com/54493278/86397015-a3702580-bcc0-11ea-99b9-2a0fe190c080.jpg)

**Comment by mlwbd** [comment]
Thanks man, I didn't tried on pc browser. It is equally optimised for phone and pc browser..?

**Comment by tks18** [comment]
> Thanks man, I didn't tried on pc browser. It is equally optimised for phone and pc browser..?

Ya ya, I Have optimized the Website for Both for Mobile and Pc. If You want to try it Use the Production Version to Try

**Comment by mlwbd** [comment]
any space for using TMDB or OMDB api for video content. Not sure is it possible.

**Comment by tks18** [comment]
> any space for using TMDB or OMDB api for video content. Not sure is it possible.

I also planned that And Its easy to setup that api.
Will see that in coming updates.
One thing is file names matter, content should be well organised, then we can send the file name and get data.

**Comment by mlwbd** [comment]
So some audio format are not supported but fine,
Also pdf are not supported.

**Comment by tks18** [comment]
Can you tell me which audio formats. 
And in case for pdf, only download is available

**Comment by mlwbd** [comment]
Yeah sure, so I randomly search for a movie.
And it have AC3 6ch audio support. And it's muted all time .
Search for Bajirao mastani and take a look
Also in cartoon section, I tried ultimate Spider-Man, and that too muted

**Comment by tks18** [comment]
Ok thanks 
Will look into that and will add that audio format

**Comment by mlwbd** [comment]
Hey, can you add me to the td for managing the files
