### ISSUE TITLE
Getting 'Unauthorized' Error

### ISSUE THREAD

**Issue by ssnjrthegr8** [tks18/gindex-v4#85]
I setup the frontend (cf workers) and backend and through heroku logs I can see that the frontend is communicating with the backend but whenever I try to request or login it shows up as 'unauthorized'. In the homepage when I enter my root user email it directs me to the login page, this means its communicating with the database but I can't login or request access. I wonder why? I am on v7.5.1

**Comment by tks18** [comment]
Have you set this env variable in the backend
FRONTENDURL
This should be your cloudflare workers site
Note: this url must have https ot http and do not put a / at the end of the url.

**Comment by ssnjrthegr8** [comment]
Yeah! It works now! Also I will leave this here for others: 
> You gotta make sure that you login through same the link you inputted into FRONTENDURL, even a difference of http or https can give you the unauthorized error.
