### ISSUE TITLE
Drive issue No showing files

### ISSUE THREAD

**Issue by theRay1s** [tks18/gindex-v4#94]
Is it necessary to write 

id : folder id ( I leave it empty or is it necessary)
name : is it necessary to be same as name of folder on drive

**Comment by theRay1s** [comment]
One more thing website is showing error while requesting access

**Comment by tks18** [comment]
> Is it necessary to write
> 
> id : folder id ( I leave it empty or is it necessary)
> name : is it necessary to be same as name of folder on drive

Yes id is required, if thats empty then your drive's personal files will listed.
Name can be anything, you can keep whatever name you want

**Comment by tks18** [comment]
> One more thing website is showing error while requesting access

What error popping up, a screenshot may help

**Comment by theRay1s** [comment]
![Screenshot_20200706-152158_Gallery](https://user-images.githubusercontent.com/54594678/86580735-baeb2f00-bf9c-11ea-82a5-9eca99d76a32.png)


This check

**Comment by theRay1s** [comment]
@tks18 bro I have tried everything but drive files are not showing up in index

When I tap on go to drive it loads it but again get back to home without showing anything

**Comment by tks18** [comment]
> ![Screenshot_20200706-152158_Gallery](https://user-images.githubusercontent.com/54594678/86580735-baeb2f00-bf9c-11ea-82a5-9eca99d76a32.png)
> 
> This check

Be sure to use my latest released version in my repo change that in your worker file,
 thats the problem

**Comment by tks18** [comment]
> @tks18 bro I have tried everything but drive files are not showing up in index
> 
> When I tap on go to drive it loads it but again get back to home without showing anything

Thats because either the client id is wrong or file id is wrong or client secret is wrong, 
Server is giving response other than 200, 
Check that every details is correct

**Comment by theRay1s** [comment]
@tks18 on how many do I have to change version

**Comment by theRay1s** [comment]
@tks18 user access is fixed I have to check drive now thanks

**Comment by tks18** [comment]
> @tks18 on how many lines do I have to change version

Check my latest worker file for any changes,
Change the version to latest

**Comment by theRay1s** [comment]
@tks18 how to push updates to bot

Or will it automatically update I just have to update the version every time u release new

**Comment by tks18** [comment]
You just have the change the version in worker file thats all

**Comment by theRay1s** [comment]
@tks18 u can close the issue 
All my problems are fixed
