### ISSUE TITLE
Team Drives/Folders  Not Switching 🤔

### ISSUE THREAD

**Issue by Nenokkadine** [tks18/gindex-v4#97]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/65813999/86804476-95415100-c094-11ea-8346-9cb08c400927.gif)

**Comment by tks18** [comment]
Ok will look through that 
Btw for mee it got switched

**Comment by Nenokkadine** [comment]
When i change the drive ID Manually in the URL it Works. But Not Changing through interactive UI

**Comment by tks18** [comment]
Ok i understood, will give a fix for this 🤟
