### ISSUE TITLE
Search box not showing.

### ISSUE THREAD

**Issue by paduhq** [tks18/gindex-v4#98]
Hello! Thank you for this awesome repo! However, after I complete publishing the app from workers, my site doesn't have the search box after I login. I used Aicirou's version before and it has the same problem. Do you know why ? 

![Screenshot_2020-07-08_00-53-30](https://user-images.githubusercontent.com/63902328/86860993-8d45d900-c0b5-11ea-98b1-f8b2da56f2a1.png)
(Your site)

![Screenshot_2020-07-08_00-53-58](https://user-images.githubusercontent.com/63902328/86860998-9040c980-c0b5-11ea-907a-c8e79a208a55.png)
(My site)

**Comment by Nenokkadine** [comment]
+1 Same for me too.

**Comment by tks18** [comment]
Bro what type of drive you use in this 
Either personal or team drive or a folder. 
If you use team drive it will be visible

**Comment by Nenokkadine** [comment]
> Bro what type of drive you use in this
> Either personal or team drive or a folder.
> If you use team drive it will be visible

I Used a Folder ID Inside Team Drive :)

**Comment by tks18** [comment]
> > Bro what type of drive you use in this
> > Either personal or team drive or a folder.
> > If you use team drive it will be visible
> 
> I Used a Folder ID Inside Team Drive :)

Folders are not supported for search thats a api restriction
 use root of team drive

**Comment by Nenokkadine** [comment]
Thanks got it

**Comment by paduhq** [comment]
> Bro what type of drive you use in this
> Either personal or team drive or a folder.
> If you use team drive it will be visible

I use folder ID with personal drive. So search box only appear for Team Drive?

**Comment by tks18** [comment]
> > Bro what type of drive you use in this
> > Either personal or team drive or a folder.
> > If you use team drive it will be visible
> 
> I use folder ID with personal drive. So search box only appear for Team Drive?

Bro if you use root of your personal drive, search will appear. 
Folders are not supported for search
